version: "3.8"
services:
  database:
    image: "mysql:5.6"
    networks:
      - backend
    environment:
      - MYSQL_DATABASE=spring_social
      - MYSQL_ROOT_PASSWORD=pass
    ports:
      - "3306:3306"

  spring-social:
    build: spring-social/
    image: "andreformento/spring-social"
    # volumes:
    #   - ./spring-social/src/main/resources/application.yml:/app/config/application.yml
    networks:
      - backend
    environment:
      - DATABASE_HOST=database
      - APP_AUTH_TOKENSECRET=666DO9292330DD5842909851AC1BDGTR
      - APP_AUTH_TOKENEXPIRATIONMSEC=864000000
    env_file: .env
    depends_on:
      - database
    ports:
      - "8080:8080"

  react-social:
    build: react-social/
    image: "andreformento/react-social"
    volumes:
      - ./react-social/public:/usr/src/app/public:ro
      - ./react-social/src:/usr/src/app/src:ro
    networks:
      - backend
    depends_on:
      - spring-social
    ports:
      - "3000:3000"

networks:
  backend:
